name: Deploy Elara API

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: elara-api-dev
  RESOURCE_GROUP: rg-elara-dev
  NODE_VERSION: '18'

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      
      - name: Install dependencies
        run: |
          cd api
          npm ci --production
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to staging
        run: |
          cd api
          zip -r ../staging-deploy.zip . -x "node_modules/.cache/*" "*.log"
          az webapp deploy \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --slot staging \
            --src-path ../staging-deploy.zip \
            --type zip \
            --restart true \
            --clean true
      
      - name: Test staging
        run: |
          sleep 45
          curl -f https://elara-api-dev-staging.azurewebsites.net/health

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      
      - name: Install dependencies
        run: |
          cd api
          npm ci --production
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to staging first
        run: |
          cd api
          zip -r ../prod-deploy.zip . -x "node_modules/.cache/*" "*.log"
          az webapp deploy \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --slot staging \
            --src-path ../prod-deploy.zip \
            --type zip \
            --restart true \
            --clean true
      
      - name: Test staging before swap
        run: |
          sleep 45
          curl -f https://elara-api-dev-staging.azurewebsites.net/health
      
      - name: Swap to production
        run: |
          az webapp deployment slot swap \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --slot staging
      
      - name: Verify production
        run: |
          sleep 15
          curl -f https://elara-api-dev.azurewebsites.net/health
