name: Deploy Elara API

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      
      - name: Install dependencies
        run: |
          cd api
          npm ci --production
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to staging
        run: |
          cd api
          tar -czf ../deploy.tar.gz .
          az webapp deploy \
            --resource-group rg-elara-dev \
            --name elara-api-dev \
            --slot staging \
            --src-path ../deploy.tar.gz \
            --type tar \
            --restart true \
            --clean true
      
      - name: Test staging
        run: |
          sleep 30
          curl -f https://elara-api-dev-staging.azurewebsites.net/health

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      
      - name: Install dependencies
        run: |
          cd api
          npm ci --production
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to staging first
        run: |
          cd api
          tar -czf ../deploy.tar.gz .
          az webapp deploy \
            --resource-group rg-elara-dev \
            --name elara-api-dev \
            --slot staging \
            --src-path ../deploy.tar.gz \
            --type tar \
            --restart true \
            --clean true
      
      - name: Test staging
        run: |
          sleep 30
          curl -f https://elara-api-dev-staging.azurewebsites.net/health
      
      - name: Swap to production
        run: |
          az webapp deployment slot swap \
            --resource-group rg-elara-dev \
            --name elara-api-dev \
            --slot staging
      
      - name: Test production
        run: |
          sleep 15
          curl -f https://elara-api-dev.azurewebsites.net/health
